---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | default "default" | quote }}
  labels:
    {{- include "irs-frontend-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "irs-frontend-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "irs-frontend-service.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "irs-frontend-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: default
              containerPort: 3000
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /
              port: default
            initialDelaySeconds: 100
            periodSeconds: 3
            failureThreshold: 3
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /
              port: default
            initialDelaySeconds: 60
            periodSeconds: 3
            failureThreshold: 3
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}
          volumeMounts:
            - name: configuration
              mountPath: /opt/app/.env
              subPath: .env
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
        - name: configuration
          configMap:
            name: {{ .Chart.Name }}
            items:
              - key: config.env
                path: .env

