---
apiVersion: v2
name: irs
description: A Helm chart for Kubernetes

type: application
version: 0.0.1
appVersion: "1.0.0"

dependencies:

  # IRS Frontend Service
  - name: irs-frontend-service
    alias: irs-frontend-service
    version: 0.0.1
    repository: https://emiladrianc.github.io/irs-frontend
    condition: install.irs.frontend
